
name: Publish Docker image

on:
  push:
    branches:
      - main


jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: build and upload images
        run: |
          docker build -t pecoret-server server
          docker login ${{ secrets.CONTAINER_REGISTRY }} --username ${{ secrets.PACKAGING_USERNAME }} --password ${{ secrets.PACKAGING_TOKEN }}
          docker tag pecoret-server ${{ secrets.CONTAINER_REGISTRY }}/pecoret/pecoret-server:dev
          docker push ${{ secrets.CONTAINER_REGISTRY }}/pecoret/pecoret-server:dev
          docker build -t pecoret-frontend frontend
          docker login ${{ secrets.CONTAINER_REGISTRY }} --username ${{ secrets.PACKAGING_USERNAME }} --password ${{ secrets.PACKAGING_TOKEN }}
          docker tag pecoret-frontend ${{ secrets.CONTAINER_REGISTRY }}/pecoret/pecoret-frontend:dev
          docker push ${{ secrets.CONTAINER_REGISTRY }}/pecoret/pecoret-frontend:dev
