name: Generate API Schema

on:
  push:
    branches: [ main ]
    tags:
      - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Tests
        run: |
          cd server
          mkdir /dist
          python manage.py migrate --settings conf.settings_testing
          python manage.py spectacular --settings conf.settings_testing --file /dist/schema.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: schema.yaml
          path: /dist/schema.yaml
