name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: true
    - name: Install Dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate schema
      run: |
        cd server
        mkdir dist
        python manage.py migrate
        python manage.py spectacular > dist/schema.yaml
    - name: Upload package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: schema-artifact
        path: server/dist/*